### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by Pr0gmaT1k**
Following this issue: #19  

Remove LCP reference and clean some unused frameworks.

Build & run.

### CODE REVIEW

**Comment by Pr0gmaT1k** [comment]
if i do that it's not properly a "fix build" ^^

**Comment by aferditamuriqi** [comment]
then maybe just submit the

 -import ReadiumLCP

as proper PR, since "fix build" will not fix the build in general.

**Comment by Pr0gmaT1k** [comment]
A PR just for one line is maybe overrated ^^.

I think the best option is to manage as you want the .pbxproj to fix properly the build and remove manually the import.

If you agree, i let you close this PR.

**Comment by aferditamuriqi** [comment]
closing this PR. build fixes will be reviewed throughout the project.

**Pull request closed without merging**
